---
title: "General Social Survey"
author: "LBS-MAM22 Group 5"
date: "2021-09-19"
tags: ["data_visualisation","statistics"]
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>A group project analysing gender, education level and email usage related with the social media preference (Instagram, Snapchat, Twitter)</p>
<!--more-->
<div id="general-social-survey-gss" class="section level1">
<h1>General Social Survey (GSS)</h1>
<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>We analyzed data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and therefore we filtered the data into a smaller file.</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))</code></pre>
<p>We noticed that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<p>We will be creating 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>We would like to estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016, by following the below steps:</p>
<ol style="list-style-type: decimal">
<li><p>Create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in your new variable should also be NA.</p></li>
<li><p>Calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</p></li>
<li><p>Using the CI formula for proportions, please construct 95% CIs for men and women who used either Snapchat or Instagram</p></li>
</ol>
<pre class="r"><code>#Step 1
gss&lt;-gss %&gt;% mutate(snap_insta = case_when(
  (snapchat ==&quot;Yes&quot; | instagrm == &quot;Yes&quot;) ~ &quot;Yes&quot;,
  (snapchat ==&quot;No&quot; &amp; instagrm == &quot;No&quot;) ~ &quot;No&quot;,
  T ~ &quot;NA&quot;))

#Step 2
gss %&gt;% 
  filter(!snap_insta == &quot;NA&quot;) %&gt;% 
  count(snap_insta, sort=TRUE) %&gt;% 
  mutate(prop = n/sum(n))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   snap_insta     n  prop
##   &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt;
## 1 No           858 0.625
## 2 Yes          514 0.375</code></pre>
<pre class="r"><code># se for proportion = sqrt (P*(1-P)/n)

#Step 3
se_prop = sqrt(
  0.625 * 0.375 / (514+858)
)

conf_low &lt;-  0.375 - 1.96 * se_prop
conf_high &lt;- 0.375 + 1.96 * se_prop

conf_high</code></pre>
<pre><code>## [1] 0.401</code></pre>
<pre class="r"><code>conf_low</code></pre>
<pre><code>## [1] 0.349</code></pre>
<p>We are 95% confident that the true proportion of instagram or snap users falls between 0.349 and 0.401.</p>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Next, we estimated the <em>population</em> proportion of Twitter users by education level in 2016.</p>
<ol style="list-style-type: decimal">
<li>Calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
<li>Using the CI formula for proportions, please construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
<li>Do these two Confidence Intervals overlap?</li>
</ol>
<pre class="r"><code>#Turn `degree` from a character variable into a factor variable
#Create a  new variable, `bachelor_graduate` to indicate if the respondent is bachelor or graduate
gss &lt;- gss %&gt;%  
  mutate(degree = factor(degree, levels=c(&quot;Lt high school&quot;,&quot;High school&quot;, &quot;Junior college&quot;, &quot;Bachelor&quot;, &quot;Graduate&quot;)),
                       bachelor_graduate = case_when(
  (degree ==&quot;Bachelor&quot; | degree == &quot;Graduate&quot;) ~ &quot;Yes&quot;,
  (degree != &quot;Bachelor&quot; &amp; degree != &quot;Graduate&quot;) ~ &quot;No&quot;,
  T ~ &quot;NA&quot;))

#Calculate the proportion of `bachelor_graduate` who do (Yes) and who don&#39;t (No) use twitter
gss %&gt;% filter(bachelor_graduate == &quot;Yes&quot;) %&gt;%
  filter(twitter != &quot;NA&quot;) %&gt;%
  count(twitter, sort=TRUE) %&gt;% 
  mutate(prop = n/sum(n))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   twitter     n  prop
##   &lt;chr&gt;   &lt;int&gt; &lt;dbl&gt;
## 1 No        375 0.767
## 2 Yes       114 0.233</code></pre>
<pre class="r"><code>#Using the CI formula for proportions
se_prop_usetwitter = sqrt(
  0.767 * 0.233 / (114+375)
)

se_prop_notwitter = sqrt(
  0.767 * 0.233 / (375+144)
)


conf_low_usetwitter &lt;-  0.233 - qt(0.975, 113) * se_prop_usetwitter
conf_high_usetwitter &lt;- 0.233 + qt(0.975, 113) * se_prop_usetwitter

conf_low_notwitter &lt;-  0.767 - qt(0.975, 374) * se_prop_notwitter
conf_high_notwitter &lt;- 0.767 + qt(0.975, 374) * se_prop_notwitter


conf_low_notwitter</code></pre>
<pre><code>## [1] 0.731</code></pre>
<pre class="r"><code>conf_high_notwitter</code></pre>
<pre><code>## [1] 0.803</code></pre>
<pre class="r"><code>conf_low_usetwitter</code></pre>
<pre><code>## [1] 0.195</code></pre>
<pre class="r"><code>conf_high_usetwitter</code></pre>
<pre><code>## [1] 0.271</code></pre>
<p>The 95% confidence interval for the proportion of bachelors and graduates that do not use twitter is 0.731 to 0.803.</p>
<p>The 95% confidence interval for the proportion of bachelors and graduates that do use twitter is 0.195 to 0.271.</p>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Next we estimated the <em>population</em> parameter on time spent on email weekly.</p>
<p>The mean of the number of minutes spent on email weekly is 417 minutes and the median is 120 minutes. The median is a better measure of the typical amount of time Americans spent on email weekly as the mean is substantially increased due to the outliers of extremely high email usage. Multiple individuals claimed to spend more than 4000 minutes on email weekly which skews the mean higher. The median is a more accurate representation of typical usage as it isn’t affected by the outliers.</p>
<p>The 95% CI for the mean weekly email time is 6 hours and 25 minutes to 7 hours and 33 minutes. There does not seem to be an odd result. The mean of the dataset is 6hrs and 57 minutes which falls into this CI.</p>
<p>One would expect a 99% confidence interval to be wider than the 95% CI. This is because to be more certain about the values of the mean weekly email time it is necessary to increase the range and hence have a wider interval. Also mathematically the t-critical value is larger and hence the CI is wider.</p>
<pre class="r"><code>set.seed(1234)
#Converts email hr and email min into one variable called email
gss &lt;- gss %&gt;%
  mutate(email = as.numeric(emailhr) * 60 + as.numeric(emailmin))
#Creates histogram showing the distribution of email
gss %&gt;%
  ggplot(aes(x=email)) +
  geom_histogram() + labs(title = &quot;Histogram of Time spent on email&quot;,
                          x= &quot;Minutes spent on email&quot;)</code></pre>
<p><img src="/groupwork/Statistic_CI/General_social_survey_files/figure-html/unnamed-chunk-3-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>gss %&gt;% summarise(meanEmail = mean(email, na.rm=TRUE),
                  medianEmail = median(email, na.rm=TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 2
##   meanEmail medianEmail
##       &lt;dbl&gt;       &lt;dbl&gt;
## 1      417.         120</code></pre>
<pre class="r"><code>#Bootstrap creating a 95% confidence interval for the mean weekly email usage.
boot_email &lt;- gss %&gt;%
  specify(response = email) %&gt;%
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;) %&gt;%
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)

boot_email</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     385.     453.</code></pre>
<pre class="r"><code>hours = boot_email%/%60 #Calculates the hours using integer division (61 minutes will give 1 hour)
minutes = round(boot_email%%60) # Calculates hours using modulus division (getting remainder) (61 min will give 1 minute)

paste(hours, &quot;hours&quot;, minutes, &quot;minutes&quot;) # function to paste the values for the confidence interval: &quot;6 hours 25 minutes&quot; &quot;7 hours 33 minutes&quot;</code></pre>
<pre><code>## [1] &quot;6 hours 25 minutes&quot; &quot;7 hours 33 minutes&quot;</code></pre>
<pre class="r"><code># wider 
#Bootstrap creating a 99% confidence interval for the mean weekly email usage.
# boot_email2 &lt;- gss %&gt;%
#   specify(response = email) %&gt;%
#   generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
#   calculate(stat = &quot;mean&quot;) %&gt;%
#   get_confidence_interval(level = 0.99, type = &quot;percentile&quot;)
# boot_email2</code></pre>
</div>
</div>
<div id="team-members" class="section level1">
<h1>Team members</h1>
<ul>
<li>Alex Kubbinga</li>
<li>Clara Moreno Sanchez</li>
<li>Jean Huang</li>
<li>Raghav Mehta</li>
<li>Raina Doshi</li>
<li>Yuan Gao</li>
</ul>
</div>
