---
title: "Youth Risk Behavior Surveillance"
author: "LBS-MAM22 Group 5"
date: "2021-09-18"
tags: ["hypo-testing"]
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>A group project exploring the relationship between the frequency of physical exercises and the weight for a typical high-schooler</p>
<!--more-->
<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. We will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<pre class="r"><code>?yrbss</code></pre>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, …
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
<p>Now we summarize the statistics of numerical variables, and create a very rough histogram.</p>
<pre class="r"><code>skim(yrbss)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-3">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>We first start with analyzing the <code>weight</code> of participants in kilograms. From the histogram and summary statistics below we can see the distribution of weights is positively skewed. We can see that the distribution is right skewed and there are 1004 missing values.</p>
<pre class="r"><code># stats
summary(yrbss$weight)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##      30      56      64      68      76     181    1004</code></pre>
<pre class="r"><code># plot histogram
yrbss %&gt;% 
  filter(!is.na(weight)) %&gt;% 
  ggplot(aes(x=weight))+
  geom_histogram(bins=30)+
  NULL</code></pre>
<p><img src="/project/Statistics_Hypotesting/Youth_risk_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity. Next we plot the data to quickly visualize trends, identify strong associations, and develop research questions.</p>
<p>We create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise.</p>
<pre class="r"><code>yrbss &lt;- yrbss %&gt;% 
  mutate(physical_3plus = case_when(
    physically_active_7d &gt;= 3 ~ &quot;yes&quot;,
    physically_active_7d &lt; 3 ~ &quot;no&quot;,
    T ~ &quot;NA&quot;
  )) %&gt;% 
  filter(physical_3plus!=&quot;NA&quot;) # remove null values



# group by and summarise
yrbss_prop &lt;- yrbss %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(n = n()) %&gt;% 
  mutate(prop= n/sum(n))
  
# another way: count
# yrbss_prop &lt;- yrbss %&gt;%
#  count(physical_3plus, sort=TRUE) %&gt;%
#  mutate(prop= n/sum(n))
yrbss_prop</code></pre>
<pre><code>## # A tibble: 2 x 3
##   physical_3plus     n  prop
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt;
## 1 no              4404 0.331
## 2 yes             8906 0.669</code></pre>
<div id="calculating-confidence-interval" class="section level3">
<h3>Calculating confidence interval</h3>
<pre class="r"><code># notes: here std_error is the standard deviation of the sample mean

not_prop &lt;- yrbss_prop %&gt;% 
  filter(physical_3plus==&quot;no&quot;) %&gt;%
  pull(&quot;prop&quot;)

not_n &lt;- yrbss_prop %&gt;% 
  filter(physical_3plus==&quot;no&quot;) %&gt;%
  pull(&quot;n&quot;)

# estimation of sd
std_error &lt;- sqrt(not_prop * (1-not_prop) / (sum(yrbss_prop$n) ))

# with unknown population sd, use t distribution 1.960503
t_critical &lt;- qt(0.975, not_n - 1)

margin_of_error &lt;- t_critical * std_error

# ci
phy_3plus_low &lt;- not_prop - margin_of_error
phy_3plus_high &lt;- not_prop + margin_of_error

print(sprintf(&quot;95%% confidence interval is [%f,%f]&quot;,phy_3plus_low,phy_3plus_high))</code></pre>
<pre><code>## [1] &quot;95% confidence interval is [0.322883,0.338875]&quot;</code></pre>
<ul>
<li>95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week is [0.322883,0.338875]</li>
</ul>
</div>
<div id="boxplot" class="section level3">
<h3>Boxplot</h3>
<p>Next we make a boxplot of <code>physical_3plus</code> vs. <code>weight</code> to check the relationship between these two variables.</p>
<pre class="r"><code>yrbss %&gt;%
  filter(physical_3plus!=&quot;NA&quot;) %&gt;% 
  ggplot(aes(x = physical_3plus , y = weight)) +
  geom_boxplot()+
  labs(title = &quot;Boxplot of Active for at least 3 days vs Weight&quot;,
       x = &quot;Active at least 3 days&quot;,
       y = &quot;Weight&quot;)+
  NULL</code></pre>
<p><img src="/project/Statistics_Hypotesting/Youth_risk_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Conclusion:</p>
<ul>
<li><p>No significant relationship can be identified. We expected the more students exercise the lighter weight they have.</p></li>
<li><p>But we can see that the median weight of the sample who are physically active for at least three days is greater than the median of the sample who are active for lesser than three days. This may be because of higher weight of muscle or bone due to working out/exercising.</p></li>
</ul>
</div>
</div>
<div id="confidence-interval-difference-of-means" class="section level2">
<h2>Confidence Interval (Difference of means)</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test.</p>
<pre class="r"><code>yrbss_stats &lt;- favstats(weight~physical_3plus, data=yrbss,na.rm = T)

# use formulas
yrbss_stats_alt &lt;- yrbss %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(avg_weight = mean(weight,na.rm=T),
            sd_weight_mean = sd(weight,na.rm=T),
            n=n())

#approximate by 1.96
t_critical &lt;- 1.96 # qt(0.975, ) # calculate df with Welch-Satterhwaite formula

no_ci_lower &lt;- 66.674 - t_critical*17.638/sqrt(sum(yrbss_stats_alt$n))
no_ci_higher &lt;- 66.674 + t_critical*17.638/sqrt(sum(yrbss_stats_alt$n))
print(sprintf(&quot;weights of &#39;no&#39;: 95%% confidence interval is [%f,%f]&quot;,no_ci_lower,no_ci_higher))</code></pre>
<pre><code>## [1] &quot;weights of &#39;no&#39;: 95% confidence interval is [66.374349,66.973651]&quot;</code></pre>
<pre class="r"><code>yes_ci_lower &lt;- 68.448 - t_critical*16.478/sqrt(sum(yrbss_stats_alt$n))
yes_ci_higher &lt;- 68.448 + t_critical*16.478/sqrt(sum(yrbss_stats_alt$n))
print(sprintf(&quot;weights of &#39;yes&#39;: 95%% confidence interval is [%f,%f]&quot;,yes_ci_lower,yes_ci_higher))</code></pre>
<pre><code>## [1] &quot;weights of &#39;yes&#39;: 95% confidence interval is [68.168056,68.727944]&quot;</code></pre>
<ul>
<li>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</li>
</ul>
</div>
<div id="hypothesis-test-with-formula-difference-of-means" class="section level2">
<h2>Hypothesis test with formula (Difference of means)</h2>
<p>Null hypothesis <span class="math inline">\(H_0:\bar{weight}_{&gt;=3h}-\bar{weight}_{&lt;3h}=0\)</span></p>
<p>Alternative hypothesis <span class="math inline">\(H_1:\bar{weight}_{&gt;=3h}-\bar{weight}_{&lt;3h}\neq0\)</span></p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss) # assume different variance</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we use <code>hypothesize</code> for conducting hypothesis tests.</p>
<p>First, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))

obs_diff</code></pre>
<pre><code>## # A tibble: 1 x 1
##    stat
##   &lt;dbl&gt;
## 1  1.77</code></pre>
<p>The statistic we are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After initializing the test, we will simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- yrbss %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()+
  NULL</code></pre>
<p><img src="/project/Statistics_Hypotesting/Youth_risk_files/figure-html/unnamed-chunk-4-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we will visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77. We will also calculate the p-value for the hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/project/Statistics_Hypotesting/Youth_risk_files/figure-html/unnamed-chunk-5-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<ul>
<li><p>In 1000 permutations, there is no point has a difference of at least <code>obs_stat</code> of 1.77. The p-value here is given by 0, but this result is an approximation based on the number of <code>reps</code> chosen in the <code>generate()</code> step.</p></li>
<li><p>Since the p_value is close to 0, we will reject the null hypothesis.</p></li>
</ul>
</div>
</div>
<div id="team-members" class="section level1">
<h1>Team members</h1>
<ul>
<li>Alex Kubbinga</li>
<li>Clara Moreno Sanchez</li>
<li>Jean Huang</li>
<li>Raghav Mehta</li>
<li>Raina Doshi</li>
<li>Yuan Gao</li>
</ul>
</div>
